export const REGISTER = {
    LOADING : 'REGISTER_LOADING',
    SUCCESS: 'REGISTER_SUCCESS',
    ERROR: 'REGISTER_ERROR'



}

export const LOGIN = {
    LOADING: 'LOGIN_LOADING',
    SUCCESS: 'LOGIN_SUCCESS',
    ERROR: 'LOGIN_ERROR'
}

export const LOGOUT = {

    USER: 'LOGOUT_USER'
    
}