export const REGISTER = {
    LOADING : 'REGISTER_LOADING',
    SUCCESS: 'REGISTER_SUCCESS',
    ERROR: 'REGISTER_ERROR'



}

export const LOGIN = {
    LOADING: 'LOGIN_LOADING',
    SUCCESS: 'LOGIN_SUCCESS',
    ERROR: 'LOGIN_ERROR'
}

export const LOGOUT = {

    LOGOUT: 'LOGOUT_USER'
    
}

export const CONTACTS = {
    LOADING: 'CONTACTS_LOADING',
    SUCCESS: 'CONTACTS_LOAD_SUCCESS',
    ERROR: 'CONTACTS_LOAD_ERROR'

}

export const ADD = {
    LOADING: 'ADD_CONTACT_LOAD',
    SUCCESS: 'ADD_CONTACT_SUCCESS',
    ERROR: 'ADD_CONTACT_ERROR',
    CLEAR: 'CLEAR_ADD_CONTACT'

}


export const SEARCH = {
    SEARCH_CONTACTS : 'SEARCH_CONTACTS'

}